version: "2.4"
services:
  mockserver:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 80:1080
    envoronment:
      MOCKSERVER_PROPERTY_FILE:  /config/mockserver.properties
    volumes:
      - type: bind
        source: .
        target: /config